version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean install
artifacts:
  files:
    - target/sample-api-0.0.1-SNAPSHOT.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
